### ISSUE TITLE
thunderlink on mac (blocked by upstream bug, but interoperability working)

### ISSUE THREAD

**Issue by christofnaegele** [mikehardy/thunderlink#20]
I have installed the beta on a mac (high sierra). I get a link, e.g. thunderlink://messageid=006201d474e4$82f16290$88d427b0$@something-else. 
But: Clicking on the link does not work: No app found which is associated with that link to open it. 
Is there a solution?

**Comment by mikehardy** [comment]
Registering an app as a protocol handler is harder these days but this may work https://superuser.com/questions/548119/how-do-i-configure-custom-url-handlers-on-os-x/548122#comment1955941_644593 could you try the referenced app and report back?

**Comment by christofnaegele** [comment]
I tried it - without success.

**Comment by mikehardy** [comment]
Oh no, that's a bummer. Well, I've started using my mac more but I have had really terrible luck registering protocol handlers with modern macOS versions - you can see all the hoops I (and a group of others) have tried here: https://smoove-operator.blogspot.com/2011/06/open-links-from-external-applications.html

May I ask exactly what you steps you followed to register the thunderlink protocol? That could help figure out a repeatable process

**Comment by mikehardy** [comment]
I still don't have a good solution for using thunderbird *on* macOS but I wrote up how I successfully interoperate between Mail.app/macOS and Thunderbird/Ubuntu here:

https://github.com/mikehardy/thunderlink/wiki/macOS-compatibility---interoperability

**Comment by mikehardy** [comment]
Turns out Thunderlink on the mac will never be able to open links correctly in Thunderbird itself because of this issue which was just solved for nightly builds: https://bugzilla.mozilla.org/show_bug.cgi?id=469990

It appears to me that they already have Thunderbird 64 in beta, and I'm not sure if this very low-level toolkit change will work its way into TB64, or if this won't show up until whatever release is after that. Someone using Thunderbird on the Mac will have to eventually indicate when this could work, until then, the interoperability mode I documented at the link above (and use myself personally!) is the way to do it.

Luckily Mail.app isn't too bad. In fact, I wrote an Applescript long ago that creates messageid links identical to the ones I show interoperation with above and you can find it here: http://smoove-operator.blogspot.com/2011/05/gtd-automating-addition-new-email-info.html

In that way you can still generate clickable links for both platforms, originating from both Mail clients. Fragmented setup perhaps but it gets the job done.

**Comment by mikehardy** [comment]
Believe it or not, @MarioKusek found a solution for this for Thunderbird 60, and it will be implemented in 1.2.7 - it's already merged now
