### ISSUE TITLE
How to add a custom target (markdown)?

### ISSUE THREAD

**Issue by duckunix** [mikehardy/thunderlink#38]
Awesome plugin.  Really helping me out.

I think I am missing something.  I would like to generate a markdown style to paste into an application, so  something like:
`[subject](thunderlink:.....)`

Is this possible?

Thanks!

**Comment by mikehardy** [comment]
Hi there - glad you like it. I thought it was useful for me that I took over maintaining it recently but I apologize that because of that I don't know all the nooks and crannies yet.

@MarioKusek Maybe you know the answer to this since you played with the templating more than I did? My hunch is that it should be possible if you're careful, for instance with the escaping. Something like

```
\[<subject>\]\(<thunderlink>\)
```

But to be clear I didn't try this. Have you tried building up a little template bit by bit to see what's possible? (like first just seeing if you could do a "thunderlink" that just had a markdown piece, then adding an interpreted part (like `<subject>`), etc etc?

**Comment by duckunix** [comment]
@mikehardy thanks for the reply.  Can you kindly point me to the templating?  I gave it a quick look, and did not see any options for that.  I am on TB-60 if that makes a difference (I know lots of things got changed in 60)

**Comment by mikehardy** [comment]
@duckunix - did you try the preference dialog where you configure the links? The variables you can use are shown right there.

I tried this as the textbox value for a test:

```
[<subject>](<thunderlink>)
```

and received this on the clipboard:
```
[[mikehardy/thunderlink] How to add a custom target (markdown)? (#38)](thunderlink://messageid=mikehardy/thunderlink/issues/38/461238110@github.com)
```

Which shows me that it works more or less as expected, though as you can see there will be a possible interaction between markdown content and email subject lines (unavoidable unfortunately, the set of legal subject characters includes valid markdown characters). But it works fine. Please try it

**Comment by duckunix** [comment]
Ah...I found the prefrence menu (tools->Addon Preferences->ThunderLink), and found that the above does work for what I want.

Thanks for the help!
