### ISSUE TITLE
Clicakble links within Thunderbird  Tasks and or events

### ISSUE THREAD

**Issue by nomatica** [mikehardy/thunderlink#41]
Hello all, First let me say thank you.
As soon as I discovered this add-on I quickly knew just how powerful it can be. Currently one of the ways that I track emails that I need to respond to is by converting them to a task or to an event within Thunderbird. However I still need to search and find the message using the subject line information. This takes time. My hope was to be able to use thunderlinks within the description or the "attachment" fields. However while I can copy and paste the link is not clickable.
Am I doing something wrong?

**Comment by mikehardy** [comment]
Hmm...I have never used thunderbird tasks or events, but if you are able to paste an arbitrary link, it ...should work? Here is what I use as my thunderlink shortcut:

`<A HREF=\"<thunderlink>\"><subject></A>"`

And if you have it hooked up correctly (via the .reg files that I think you saw and are using?) is should work even if from an operating system / thunderbird perspective the chain of events is:

- thunderlink creates a link and puts it on your clipboard
- you paste it into thunderbird somewhere else, just as an arbitrary link from thunderbirds perspective
- you  click the link and thunderbird does not handle it internally, calls system link services
- system sees it as a link you have registered for thunderbird, asks thunderbird to open it
- thunderlink intercepts it and tries to get thunderbird to open it per your thunderlink configuration

I write all that out so that if there is some sort of failure you can maybe think through it and try to find where...

**Comment by nomatica** [comment]
Thanks for your detail. I am not a programmer or developer and it helps me knowing the logical path.   I used one for the "custom" options with the shortcut and it did not seem to work. I will double check.  It is almost identical to the Clickable "string 5" command
 <A HREF="<thunderlink>"><subject></A> 
This creates a clickable link, if  use the insert hyperlink option in libre office or  libre cal. I will also be clickable if I add it to the body of an email, and send it. I think it has to do with html.  My guess is that you cannot use html coding in the task/ event fields.  This guess is coming from someone who knows very little about this stuff;)

**Comment by mikehardy** [comment]
I am able to do links in events notes field at least, but the other fields are not I do not think. For me, I use toodledo (online task system) or google keep so I haven´t tested it. I'll keep listening - best way to learn is to play so good luck as you try stuff

**Comment by nomatica** [comment]
Thank you. You said you are able to do it in the "notes" field of an event? I do not have a notes field. There is a description field, which could be seen as a notes field especially given different translations of Thunderbird. I've been able to make the thunder link work if I put it in the attachments as a web location. While this requires a few extra clicks within the workflow, I could see it working nicely.
I will continue to play but right now I need to get back to work.

Toodledo and google keep are great systems. I am however looking for a system that does not require a third-party cloud service/subscription.

Thank you for all your help and development. I did post another message looking for how other people are using the thunderlink. 

Right now I'm very happy to have it working just fine tune it and figure out how to utilize it in  a workflow

**Comment by mbezzi** [comment]
Good morning Mike, may I ask you how do you use thunderlinks with Google Keep please? I managed to have them working with other applications (zim-wiki) and inside thunderbird mail messages, but when I paste a link like the one you mentioned (clickable subject) into a Google Keep note and save it, this behaves like normal text and I can't link from it. Thank you.

**Comment by mikehardy** [comment]
Very strange! This used to work but is not working now, and I'm not sure why. I use Chrome and Safari alternately as rendering backends for both Keep and Toodledo, and now Keep is showing plaintext as you describe in Chromium, and Toodledo in Safari is converting them to just text of the link - killing the actual link - if I edit existing ones. Most unexpected.

The links themselves are still working fine, just the external systems aren't playing nice right now.

I don't have more time to troubleshoot it at the moment, but if no one discovers a workaround for this they go on my naughty list and I stop using them.

**Comment by mbezzi** [comment]
Thank you Mike, I thought it was me :-)
